name: AspectAnalytics
favicon: null
layout_spectrum: 0.61999
typography_spectrum: 0.56471
title: Aspect Analytics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4e84c4'
    - '#000000'
    - '#bbbdbf'
    - '#4d82c4'
    - '#4a83c3'
  brandStrength: 0.625
  lightness: 0.8125
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
